### ISSUE TITLE
Reimplement Curnel in not-Redex.

### ISSUE THREAD

**Issue by wilbowma** [wilbowma/cur#1]
The current implementation of the Curnel expand to Redex, which is slow enough on its own, and the type-checker is exponential (at least). This is becoming a problem.

**Comment by maxsnew** [comment]
Soooo slooooow.

**Comment by wilbowma** [comment]
Have a specific example? I haven't had problems since caching judgment forms was enables, but I'd love to build up a benchmark suite.

**Comment by wilbowma** [comment]
With recent merges from issue-9, the interface between `redex-lang.rkt` and `redex-core.rkt` is clear enough, and parts of `redex-core.rkt` abstract enough, that parts of `redex-core.rkt` can be easily implemented in Racket for performance gains. 

For example, `Σ` can be converted to a Racket hash, which would provide asymptotic gains for type-checking and eliminator reduction.

Suggesting doing this in stages and retaining `redex-core.rkt` to perform random testing against. For instance, a first step may be to create `hybrid-core.rkt` and convert `Σ` to a hash.

**Comment by maxsnew** [comment]
I'm willing to help on this since I've been complaining so much about performance.

**Comment by wilbowma** [comment]
Feel free. `redex-core.rkt` is readable enough, I think.

Low hanging fruit: 

~~1. Remove contracts~~ DONE
~~2. DIY memoize `reduce`; since reduce takes `Σ` and `t` as arguments, it can fail to properly cache reduction to `t` e.g. when `Σ` is extended.~~ Rewrote interpreter in Racket, instead.
~~3. Change `Σ` and `Γ` into Racket hashes, or at least maintain a bijection.~~ Bad idea, at least doing this the low-hanging-fruit way.
4. Precompute/cache types of eliminators, store in `Σ`. May not give much gains, considering metafunction cache their results, but might since these metafunctions are vulnerable to same caching issues as `reduce`.

Less low hanging fruit:
1. Change `Ξ` to a list (maybe vector) of hashes and `Θ` list or vector, or at least maintain such bijections. May complicate typing and reduction of elimination.
2. Compile eliminator reduction. I think it should be possible to compile `(elim x U)` to a metafunction or something, rather than the current method of figuring out where the inductive applications get inserted each time `(elim x U)` takes a step. If possible, could be compiled and store in `Σ`.

**Comment by wilbowma** [comment]
Via https://twitter.com/wilbowma/status/716376222335246337:
- http://math.andrej.com/2012/11/08/how-to-implement-dependent-type-theory-i/
- Licata/Harper’s “Mechanizing Metatheory in a Logical Framework”
- http://arxiv.org/pdf/1102.2405.pdf
