### ISSUE TITLE
abstract get-match-info interface

### ISSUE THREAD

**Issue by wilbowma** [wilbowma/cur#108]
Just had to modify the match info, and change every use because it's access by pattern matching rather than a functional API. Need to fix this, but non-critical.

**Comment by stchang** [comment]
I think this is already done. It just needs to be merged. Can you see if https://github.com/stchang/cur/tree/generic-type-methods or https://github.com/stchang/cur/tree/popl2020-artifact has what you want?

**Comment by stchang** [comment]
I think I initially misunderstood the issue. But I started to implement what the issue wants in https://github.com/wilbowma/cur/commit/fe6213b4766c238beb9742a72c9d57c40e23a866 with the `datatype-info-X` extractors.
