### ISSUE TITLE
Change "master" to "main"

### ISSUE THREAD

**Issue by wilbowma** [wilbowma/cur#116]

**Comment by wilbowma** [comment]
I think this is done now. I've updated the Racket package catalog, the github entry, and copied over the branch.
nb: @stchang

**Comment by stchang** [comment]
So all old urls and scripts should be updated?

**Comment by wilbowma** [comment]
Not sure what you mean. Which scripts or URLs depended on "master"?

**Comment by stchang** [comment]
Just trying to figure out what the change is. So everything that explicitly referenced `master` won't work? Or just wont be up to date?

Yah, fortunately we werent using it for a long time so changes should be minimal.

**Comment by wilbowma** [comment]
Now, the default stable branch is named "main", so just make sure to push to "main" from now on. The only manual intervention I can think of is when we're branching etc on command line.

"main" will be the default when you clone from GitHub and open a PR, and the Racket package catalogue is already updated to install from "main", so nothing needs to change there.

**Comment by stchang** [comment]
Ok thanks. I was thinking of existing installs. Will `raco setup` still work or is a reinstall required? And do local repos need re-cloning, or config update?

Also, links to code, like in issue tickets or emails could be affected, right? (But minimal like you said. I just checked the paper and artifact doc and it's still good.)

**Comment by stchang** [comment]
sorry, the above should have said "Will `raco pkg update` still work?"

**Comment by wilbowma** [comment]
Yes, just tested.

**Comment by wilbowma** [comment]
Local repos don't need recloning; just pull and checkout "main".

Links could be affected. The master branch still exists, it's just not the default.
