### ISSUE TITLE
Cur needs parameters

### ISSUE THREAD

**Issue by wilbowma** [wilbowma/cur#22]
Can't figure out how to eliminate Or and Maybe properly. See tests in those files. Suspect eliminator is too weak.

**Comment by maxsnew** [comment]
Here's a working Maybe example

```
(define (from-may (A : Type) (default : A) (m : (Maybe A)))
  (elim Maybe Type (λ* (A : Type) (m : (Maybe A)) A)
        (λ* (A : Type) default)
        (λ* (A : Type) (a : A) a)
        A
        m))
```

**Comment by maxsnew** [comment]
Also I don't think they're too weak. I've derived the seemingly stronger ones in coq. I tried to translate it to cur but ran into https://github.com/wilbowma/cur/issues/23

We def want to generate the better elimination forms as they are MUCH easier to use.

**Comment by wilbowma** [comment]
Actually, I think we need parameters in addition to inductive types; indexed families not sufficient to express parameterized familes, nor vice versa.

**Comment by wilbowma** [comment]
Some sources:
http://www.lix.polytechnique.fr/~barras/habilitation/
https://twitter.com/wilbowma/status/699682477917499392

**Comment by wilbowma** [comment]
... coming soon ...

**Comment by wilbowma** [comment]
See implementation in https://github.com/wilbowma/cic-redex
