### ISSUE TITLE
Type inference

### ISSUE THREAD

**Issue by wilbowma** [wilbowma/cur#45]
I think this will require a new `module-begin` that can walk the module and do the necessary type inference. I worry this will duplicate code from the Curnel, although perhaps the `type-infer` API will prevent too much duplication. Even if we do end up duplicating some of the type system, the Curnel serves as the trusted checker, while the type inference would be untrusted.

An alternative approach is present in some of the work for issue #26, making each form do its own local type inference via `type-infer` and additional form specific reasoning. I doubt this scales, though.

In the end, the right solution will likely be some combination of the two.

**Comment by wilbowma** [comment]
Alexis has prototype/example type inference here:
https://gist.github.com/lexi-lambda/13eb70af9534301f84fd8b07ef717c31

Should be useful.

**Comment by stchang** [comment]
What kind of type inference is acceptable? (What is the example at that link? HM-style inference?) Cur only does very local type inference right now.

**Comment by wilbowma** [comment]
Local inference is fine. I’m quite against unification as debugging becomes a global problem.

--

**Comment by stchang** [comment]
Yes, full HM will require using `#%module-begin` and make debugging worse.

Here's an example where we try to improve local inference using both top-down and bottom up context info. It already gets a little complicated. https://github.com/stchang/macrotypes/blob/master/turnstile-example/turnstile/examples/infer.rkt

Anyhow I'm fine with the status quo too. closing
