### ISSUE TITLE
Transitivity of subtyping?

### ISSUE THREAD

**Issue by wilbowma** [wilbowma/cur#47]
I think transitivity of subtyping is broken. See http://www.cse.chalmers.se/~ulfn/papers/thesis.pdf for how to actually implement this.

**Comment by maxsnew** [comment]
Counterexample?

**Comment by wilbowma** [comment]
Wouldn't be a question if I had one; I suspect it though due to my hasty adaptation of declarative conversion rule into algorithmic rules, and due to similar bug in my cic-redex model.

**Comment by stchang** [comment]
Yes I think subtyping is working. Closing until someone comes up with a specific counterexample.
