### ISSUE TITLE
zero argument lambda

### ISSUE THREAD

**Issue by stchang** [wilbowma/cur#75]
`(lambda 1)` => `1`

This is due to not explicitly grouping the params in the lambda macro, but I'm not sure how to fix since an extra case is not enough.

**Comment by stchang** [comment]
After thinking about it some more, I can see how this is somewhat sensible from an implementation perspective. But maybe the right thing is to add another user-facing macro wrapper that makes this a syntax err?

**Comment by wilbowma** [comment]
As in, make zero argument lambdas an error so people aren't confused by the computation not being apply-able ?

I think supporting n-ary lambdas internally, or at least 0 and 1-art, would have benefits in the long run (to support effects and CBV).

--

**Comment by stchang** [comment]
Oh ok, I wasnt sure if 0-arg lambdas were supposed to be supported or not. 

Is the behavior I mentioned the expected behavior though?

(I completely understand why it behaves that way, just wasnt sure if that was intended.)

**Comment by maxsnew** [comment]
Wait what is the current behavior? seems to me `(lambda t)` should be a syntax error, whereas `(lambda () t)` should be the same things as `t` and on the application side `(t)` is the same thing as `t`

**Comment by wilbowma** [comment]
Right now, it's reversed: `(lambda t)` and `((lambda t))` are the same as `t` and `(lambda () t)` is a syntax error. It should be as @maxsnew describes it, but this is what I did when I first hacked up the multi-arity macros

**Comment by stchang** [comment]
stuck with original Cur semantics
